In [2]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [11]:
pip install kagglehub

Note: you may need to restart the kernel to use updated packages.


In [12]:
import kagglehub
import os

dataset_dir = kagglehub.dataset_download("bobaaayoung/trafficvolumedatacsv")

# Find the CSV file within the directory
for filename in os.listdir(dataset_dir):
    if filename.endswith(".csv"):
        csv_file_path = os.path.join(dataset_dir, filename)
        break  # Stop after finding the first CSV file

print("Path to CSV file:", csv_file_path)

100%|██████████| 532k/532k [00:00<00:00, 5.45MB/s]

Extracting files...
Path to CSV file: C:\Users\nilay\.cache\kagglehub\datasets\bobaaayoung\trafficvolumedatacsv\versions\1\TrafficVolumeData.csv


In [13]:
df = pd.read_csv(csv_file_path)
df.head()

date_time is_holiday  air_pollution_index  humidity  wind_speed  \
0  2012-10-02 09:00:00        NaN                  121        89           2   
1  2012-10-02 10:00:00        NaN                  178        67           3   
2  2012-10-02 11:00:00        NaN                  113        66           3   
3  2012-10-02 12:00:00        NaN                   20        66           3   
4  2012-10-02 13:00:00        NaN                  281        65           3   

   wind_direction  visibility_in_miles  dew_point  temperature  rain_p_h  \
0             329                    1          1       288.28       0.0   
1             330                    1          1       289.36       0.0   
2             329                    2          2       289.58       0.0   
3             329                    5          5       290.13       0.0   
4             329                    7          7       291.14       0.0   

   snow_p_h  clouds_all weather_type weather_description  traffic_volume  
0       0.0          40       Clouds    scattered clouds            5545  
1       0.0          75       Clouds       broken clouds            4516  
2       0.0          90       Clouds     overcast clouds            4767  
3       0.0          90       Clouds     overcast clouds            5026  
4       0.0          75       Clouds       broken clouds            4918

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33750 entries, 0 to 33749
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   date_time            33750 non-null  object 
 1   is_holiday           43 non-null     object 
 2   air_pollution_index  33750 non-null  int64  
 3   humidity             33750 non-null  int64  
 4   wind_speed           33750 non-null  int64  
 5   wind_direction       33750 non-null  int64  
 6   visibility_in_miles  33750 non-null  int64  
 7   dew_point            33750 non-null  int64  
 8   temperature          33750 non-null  float64
 9   rain_p_h             33750 non-null  float64
 10  snow_p_h             33750 non-null  float64
 11  clouds_all           33750 non-null  int64  
 12  weather_type         33750 non-null  object 
 13  weather_description  33750 non-null  object 
 14  traffic_volume       33750 non-null  int64  
dtypes: float64(3), int64(8), object(4)
m

In [15]:
# Null values
null_values = df.isnull().sum()
print("Null values:\n", null_values)


Null values:
 date_time                  0
is_holiday             33707
air_pollution_index        0
humidity                   0
wind_speed                 0
wind_direction             0
visibility_in_miles        0
dew_point                  0
temperature                0
rain_p_h                   0
snow_p_h                   0
clouds_all                 0
weather_type               0
weather_description        0
traffic_volume             0
dtype: int64


In [16]:
# List out all the unique values in the is_holiday column
unique_values = df['is_holiday'].unique()
print("Unique values in is_holiday column:", unique_values)

Unique values in is_holiday column: [nan 'Columbus Day' 'Veterans Day' 'Thanksgiving Day' 'Christmas Day'
 'New Years Day' 'Washingtons Birthday' 'Memorial Day' 'Independence Day'
 'State Fair' 'Labor Day' 'Martin Luther King Jr Day']


In [17]:
# Replace the NaN in is_holiday to "No"
df['is_holiday'].fillna('No', inplace=True)

C:\Users\nilay\AppData\Local\Temp\ipykernel_24652\3329544985.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['is_holiday'].fillna('No', inplace=True)


In [18]:
# Null values
null_values = df.isnull().sum()
print("Null values:\n", null_values)

# Unique values
unique_values = df.nunique()
print("\nUnique values:\n", unique_values)

# Numerical columns
numerical_cols = df.select_dtypes(include=['number']).columns.tolist()
print("Numerical columns:", numerical_cols)

# Categorical columns
categorical_cols = df.select_dtypes(include=['category', 'object']).columns.tolist()
print("Categorical columns:", categorical_cols)

Null values:
 date_time              0
is_holiday             0
air_pollution_index    0
humidity               0
wind_speed             0
wind_direction         0
visibility_in_miles    0
dew_point              0
temperature            0
rain_p_h               0
snow_p_h               0
clouds_all             0
weather_type           0
weather_description    0
traffic_volume         0
dtype: int64

Unique values:
 date_time              28589
is_holiday                12
air_pollution_index      290
humidity                  88
wind_speed                17
wind_direction           361
visibility_in_miles        9
dew_point                  9
temperature             5611
rain_p_h                 353
snow_p_h                  12
clouds_all                60
weather_type              11
weather_description       38
traffic_volume          6462
dtype: int64
Numerical columns: ['air_pollution_index', 'humidity', 'wind_speed', 'wind_direction', 'visibility_in_miles', 'dew_point', 'temperatu

In [19]:
# Convert the date_time column to datetime object
df_update_1 = df.copy()
df_update_1['date_time'] = pd.to_datetime(df['date_time'])

# Split date_time into two columns, date and time
df_update_1['date'] = df_update_1['date_time'].dt.date
df_update_1['time'] = df_update_1['date_time'].dt.time

# Bring the date and time columns to the front of the dataframe
df_update_1 = df_update_1[['date_time','date', 'time'] + [col for col in df_update_1.columns if col not in ['date_time', 'date', 'time']]]


In [ ]:
df_update_1.head()

date_time        date      time is_holiday  air_pollution_index  \
0 2012-10-02 09:00:00  2012-10-02  09:00:00         No                  121   
1 2012-10-02 10:00:00  2012-10-02  10:00:00         No                  178   
2 2012-10-02 11:00:00  2012-10-02  11:00:00         No                  113   
3 2012-10-02 12:00:00  2012-10-02  12:00:00         No                   20   
4 2012-10-02 13:00:00  2012-10-02  13:00:00         No                  281   

   humidity  wind_speed  wind_direction  visibility_in_miles  dew_point  \
0        89           2             329                    1          1   
1        67           3             330                    1          1   
2        66           3             329                    2          2   
3        66           3             329                    5          5   
4        65           3             329                    7          7   

   temperature  rain_p_h  snow_p_h  clouds_all weather_type  \
0       288.28       0.0       0.0          40       Clouds   
1       289.36       0.0       0.0          75       Clouds   
2       289.58       0.0       0.0          90       Clouds   
3       290.13       0.0       0.0          90       Clouds   
4       291.14       0.0       0.0          75       Clouds   

  weather_description  traffic_volume  
0    scattered clouds            5545  
1       broken clouds            4516  
2     overcast clouds            4767  
3     overcast clouds            5026  
4       broken clouds            4918

In [20]:
# Create a function to categorize time into different periods
def categorize_time(time):
    if pd.isnull(time):
        return np.nan  # Handle missing values
    hour = time.hour
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

# Apply the function to the 'time' column
df_update_2 = df_update_1.copy()
df_update_2['time_of_day'] = df_update_2['time'].apply(categorize_time)

df_update_2 = df_update_2[['date_time','date', 'time','time_of_day'] + [col for col in df_update_1.columns if col not in ['date_time', 'date', 'time','time_of_day']]]


In [21]:
df_update_2.head()

date_time        date      time time_of_day is_holiday  \
0 2012-10-02 09:00:00  2012-10-02  09:00:00     Morning         No   
1 2012-10-02 10:00:00  2012-10-02  10:00:00     Morning         No   
2 2012-10-02 11:00:00  2012-10-02  11:00:00     Morning         No   
3 2012-10-02 12:00:00  2012-10-02  12:00:00   Afternoon         No   
4 2012-10-02 13:00:00  2012-10-02  13:00:00   Afternoon         No   

   air_pollution_index  humidity  wind_speed  wind_direction  \
0                  121        89           2             329   
1                  178        67           3             330   
2                  113        66           3             329   
3                   20        66           3             329   
4                  281        65           3             329   

   visibility_in_miles  dew_point  temperature  rain_p_h  snow_p_h  \
0                    1          1       288.28       0.0       0.0   
1                    1          1       289.36       0.0       0.0   
2                    2          2       289.58       0.0       0.0   
3                    5          5       290.13       0.0       0.0   
4                    7          7       291.14       0.0       0.0   

   clouds_all weather_type weather_description  traffic_volume  
0          40       Clouds    scattered clouds            5545  
1          75       Clouds       broken clouds            4516  
2          90       Clouds     overcast clouds            4767  
3          90       Clouds     overcast clouds            5026  
4          75       Clouds       broken clouds            4918

In [22]:
df_update_3 = df_update_2.copy()
# Convert 'date' column to datetime objects before using .dt accessor
df_update_3['date'] = pd.to_datetime(df_update_3['date'])
df_update_3['day_of_week'] = df_update_3['date'].dt.day_name()

# Bring day_of_week next to date
cols = list(df_update_3.columns)
cols.remove('day_of_week')
cols.insert(cols.index('date') + 1, 'day_of_week')
df_update_3 = df_update_3[cols]


In [23]:
df_update_3.head()

date_time       date day_of_week      time time_of_day is_holiday  \
0 2012-10-02 09:00:00 2012-10-02     Tuesday  09:00:00     Morning         No   
1 2012-10-02 10:00:00 2012-10-02     Tuesday  10:00:00     Morning         No   
2 2012-10-02 11:00:00 2012-10-02     Tuesday  11:00:00     Morning         No   
3 2012-10-02 12:00:00 2012-10-02     Tuesday  12:00:00   Afternoon         No   
4 2012-10-02 13:00:00 2012-10-02     Tuesday  13:00:00   Afternoon         No   

   air_pollution_index  humidity  wind_speed  wind_direction  \
0                  121        89           2             329   
1                  178        67           3             330   
2                  113        66           3             329   
3                   20        66           3             329   
4                  281        65           3             329   

   visibility_in_miles  dew_point  temperature  rain_p_h  snow_p_h  \
0                    1          1       288.28       0.0       0.0   
1                    1          1       289.36       0.0       0.0   
2                    2          2       289.58       0.0       0.0   
3                    5          5       290.13       0.0       0.0   
4                    7          7       291.14       0.0       0.0   

   clouds_all weather_type weather_description  traffic_volume  
0          40       Clouds    scattered clouds            5545  
1          75       Clouds       broken clouds            4516  
2          90       Clouds     overcast clouds            4767  
3          90       Clouds     overcast clouds            5026  
4          75       Clouds       broken clouds            4918

In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 11.3 MB 2.5 MB/s eta 0:00:01
     |████████████████████████████████| 347 kB 3.6 MB/s eta 0:00:01
     |████████████████████████████████| 509 kB 7.7 MB/s eta 0:00:01
     |████████████████████████████████| 13.7 MB 2.4 MB/s eta 0:00:011
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd
df=pd.read_csv("traffic_data_preprocessed.csv")

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

# Split features and target
X = df_scaled.iloc[:, :-1]
y = df_scaled.iloc[:, -1]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Random Forest with a few hyperparameters
model = RandomForestRegressor(
    n_estimators=200,        # number of trees
    max_depth=10,            # limits how deep each tree can go
    min_samples_split=5,     # minimum samples to split a node
    min_samples_leaf=2,      # minimum samples at a leaf
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("R2 Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))


R2 Score: 0.15186731685850918
MSE: 0.8540671945090536


In [13]:
!pip install scikit-learn


zsh:1: command not found: pip


In [14]:
# pip install scikit-learn
df=pd.read_csv("traffic_data_preprocessed.csv")

In [16]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

# Split features and target
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize MLPRegressor with some hyperparameters
model = MLPRegressor(
    hidden_layer_sizes=(100, 50),  # two hidden layers with 100 and 50 neurons respectively
    activation='relu',             # activation function
    solver='adam',                 # optimization algorithm
    max_iter=500,                  # maximum number of iterations
    random_state=42
)

# Train the model
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate the model
print("R2 Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))


R2 Score: 0.4930545373288535
MSE: 1.2426832873377145


In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Assuming df_scaled is defined and includes your features and a categorical target
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Logistic Regression model
model = LogisticRegression(random_state=42, max_iter=1000)

# Train the model
model.fit(X_train, y_train)

# Predict the target for test data
y_pred = model.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.3983703703703704
Confusion Matrix:
 [[234  65   0  62 124   0]
 [ 92 596 147 134 610 166]
 [  0 288 210  33 338 127]
 [ 93  28   0 452 273   0]
 [151 291  67 290 786 286]
 [  0 201  89   1 105 411]]
Classification Report:
               precision    recall  f1-score   support

           0       0.41      0.48      0.44       485
           1       0.41      0.34      0.37      1745
           2       0.41      0.21      0.28       996
           3       0.47      0.53      0.50       846
           4       0.35      0.42      0.38      1871
           5       0.42      0.51      0.46       807

    accuracy                           0.40      6750
   macro avg       0.41      0.42      0.41      6750
weighted avg       0.40      0.40      0.39      6750



/Users/allisonhanlon/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Assuming df_scaled is defined and includes your features and a categorical target
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Decision Tree Classifier with some hyperparameters
model = DecisionTreeClassifier(
    max_depth=10,       # limits the depth of the tree to prevent overfitting
    min_samples_split=5,  # minimum samples required to split an internal node
    random_state=42
)

# Train the model
model.fit(X_train, y_train)

# Predict the target for test data
y_pred = model.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.6365925925925926
Confusion Matrix:
 [[ 350    4    0   47   84    0]
 [  56 1072  164  129  247   77]
 [   0   93  627   77  129   70]
 [  95   23    4  618  106    0]
 [  89  120  120  253 1147  142]
 [   0   70  113    0  141  483]]
Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.72      0.65       485
           1       0.78      0.61      0.69      1745
           2       0.61      0.63      0.62       996
           3       0.55      0.73      0.63       846
           4       0.62      0.61      0.62      1871
           5       0.63      0.60      0.61       807

    accuracy                           0.64      6750
   macro avg       0.63      0.65      0.64      6750
weighted avg       0.65      0.64      0.64      6750

